// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDW_ln-VpU_wpgEG05g9Xgu1T2lT0soY8E',
    appId: '1:86412205703:web:3e299abc80e4ef096d2222',
    messagingSenderId: '86412205703',
    projectId: 'groupchat-by-tyroget',
    authDomain: 'groupchat-by-tyroget.firebaseapp.com',
    storageBucket: 'groupchat-by-tyroget.appspot.com',
    measurementId: 'G-Y27RL544F2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKg4HWrxLB2LLH0TS8Dmc_0ocyk7FmUIA',
    appId: '1:86412205703:android:299d7076b7ddf0e56d2222',
    messagingSenderId: '86412205703',
    projectId: 'groupchat-by-tyroget',
    storageBucket: 'groupchat-by-tyroget.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDez9RlX2gP0-_LigJzU3XXAm15iaiVTsg',
    appId: '1:86412205703:ios:9038645a2b6987ed6d2222',
    messagingSenderId: '86412205703',
    projectId: 'groupchat-by-tyroget',
    storageBucket: 'groupchat-by-tyroget.appspot.com',
    iosClientId: '86412205703-ejf3p2qfvicvnl9r4mfuge7vtvnquc1r.apps.googleusercontent.com',
    iosBundleId: 'com.example.groupChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDez9RlX2gP0-_LigJzU3XXAm15iaiVTsg',
    appId: '1:86412205703:ios:9038645a2b6987ed6d2222',
    messagingSenderId: '86412205703',
    projectId: 'groupchat-by-tyroget',
    storageBucket: 'groupchat-by-tyroget.appspot.com',
    iosClientId: '86412205703-ejf3p2qfvicvnl9r4mfuge7vtvnquc1r.apps.googleusercontent.com',
    iosBundleId: 'com.example.groupChat',
  );
}
