name: create_social
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_auth: ^3.4.2
  firebase_core: ^1.20.0
  cloud_firestore: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.9.3
  flutter_native_splash: ^2.2.6

flutter_native_splash:
  
  background_image: images/stitch.png

flutter:
  uses-material-design: true
  assets:
    - images/
flutter_icons:
  android: true
  ios: true
  image_path: "images/stitch.png"
